---
title: "Collate_TidalSurvey_Data"
author: "Zoe Read"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(lubridate)
library(hms)
library(readr)
```

#Read in and collate all the files in the DOC Processed Data folder 
```{r}

files <- list.files(path = "Processed_Data", pattern = "DOC.*\\.csv$", full.names = TRUE, recursive = TRUE)

data1 <- read_csv(files[1], id = "filename", col_types = cols(.default = col_character()))
colnames(data1)

data2 <- read_csv(files[2], id = "filename", col_types = cols(.default = col_character()))
colnames(data2)

data3 <- read_csv(files[3], id = "filename", col_types = cols(.default = col_character()))
colnames(data3)
data3_formatted <- data3 %>% 
  mutate(Replicate = Sample_ID, 
         Sample_ID = sample_name, 
         Date = ymd(Sample_Date)) %>% 
  mutate(
  Time_Local = 
    ifelse(is.na(Time), NA,
    paste0(
      substr(sprintf("%04d", as.numeric(Time)), 1, 2),
      ":",
      substr(sprintf("%04d", as.numeric(Time)), 3, 4)))) %>% 
  select(-sample_name, -Time) %>% 
  mutate(across(everything(), as.character))

# data_list <- lapply(files, function(f) {
#   df <- read.csv(f, stringsAsFactors = FALSE, colClasses = "character")  # avoids factors
#   return(df)
# })

# Combine all files
DOC_data <- bind_rows(data1, data2, data3_formatted)

colnames(DOC_data)

DOC_data1 <- DOC_data %>% 
  rename(Sample_Location = Site) %>% 
  mutate(Sample_Location = ifelse(str_detect(Sample_ID, "GCW"), "Flume", Sample_Location)) %>% 
  select(Project, Sample_ID, Date, Time_Local, Sample_Location, npoc_mgL, npoc_uM, npoc_flag, tdn_mgL, tdn_uM, tdn_flag, filename)

```

#Read in and collate all the files in the DIC Processed Data folder 
```{r}

files <- list.files(path = "Processed_Data", pattern = "DIC.*\\.csv$", full.names = TRUE, recursive = TRUE)

data1 <- read_csv(files[1], id = "filename", col_types = cols(.default = col_character()))
colnames(data1)
data1 <- data1 %>% 
  mutate(Date = mdy(Date))

data2 <- read_csv(files[2], id = "filename", col_types = cols(.default = col_character()))
colnames(data2)
data2 <- data2 %>% 
  mutate(Date = mdy(Date))

data3 <- read_csv(files[3], id = "filename", col_types = cols(.default = col_character()))
colnames(data3)
data3_formatted <- data3 %>% 
  mutate(Replicate = Sample_ID, 
         Sample_ID = sample_name, 
         Date = ymd(Sample_Date)) %>% 
  mutate(
  Time_Local = 
    ifelse(is.na(Time), NA,
    paste0(
      substr(sprintf("%04d", as.numeric(Time)), 1, 2),
      ":",
      substr(sprintf("%04d", as.numeric(Time)), 3, 4)))) %>% 
  select(-sample_name, -Time) 

# Combine all files
DIC_data <- bind_rows(data1, data2, data3_formatted)
colnames(DIC_data)

DIC_data1 <- DIC_data %>% 
  rename(Sample_Location = Site) %>% 
  mutate(Sample_Location = ifelse(str_detect(Sample_ID, "GCW"), "Flume", Sample_Location)) %>% 
  select(Project, Sample_ID, Date, Time_Local, Sample_Location, Sample_Type, Replicate, Paired, ic_mgL, ic_uM, ic_flag)

```

#Read in and collate all the files in the TA Processed Data folder 
```{r}

files <- list.files(path = "Processed_Data", pattern = "TA.*\\.csv$", full.names = TRUE, recursive = TRUE)
files

data1 <- read_csv(files[1], id = "filename", col_types = cols(.default = col_character()))
colnames(data1)

data_list <- lapply(files, function(f) {
  df <- read.csv(f, stringsAsFactors = FALSE)  # avoids factors
  # df$Site <- as.character(df$Site)             # ensures character
  return(df)
})

# Combine all files
TA_data <- bind_rows(data_list)

#remove the first unneeded column
TA_data <- TA_data[, -which(names(TA_data) == "X")]

##Match DIC/DOC columns names
TA_data1 <- TA_data %>% 
  mutate(Project = "FATE", 
         TA_mmolL = Alk_GP_avg/1000, 
         Date = mdy(date), 
         Time = substr(time, 1, 5), 
         location = gsub("Marsh_weir", "Flume", location)) %>% 
  rename(Sample_Location = location) %>% 
  select(Project, Date, Time, Sample_Location, sample_id, TA_mmolL)

```

##Combine dataframes
```{r combine bottle data}

DIC_DOC <- merge(DIC_data1, DOC_data1, by = c("Project", "Date", "Time", "Sample_Location"), all = TRUE)
DIC_DOC_TA <- merge(DIC_DOC, TA_data1, by = c("Project", "Date", "Time", "Sample_Location"), all = TRUE)
DIC_DOC_TA <- DIC_DOC_TA %>% 
  rename(Time_Local = Time)

```

##Merge with metadata
```{r metadata}

meta_2025 <- read.csv("Metadata/FATE_Monitoring_Metadata_2025.csv", colClasses = "character")
meta_2026 <- read.csv("Metadata/FATE_Monitoring_Metadata_2026.csv", colClasses = "character")

meta <- bind_rows(meta_2025, meta_2026)

meta1 <- meta %>% 
  mutate(Date = mdy(Date)) %>% 
  select(-c(DIC_24ml, DIC_ex_1ml, SO4.H2S_5ml, Nutr_10ml, DOC_20ml, TA_250ml))

all_data <- DIC_DOC_TA %>% 
  left_join(meta1, by = c("Date", "Time_Local", "Sample_Location"))

```


##Collate the data 
```{#r}
colnames(all_data)

#Put together the final lysimeter data 
final_data_lys <- all_data %>%
    rename(Analysis_rundate = Analysis_runtime) %>%
    select(
    Project, Region, Site, Zone, Replicate, Depth_cm, 
         Sample_ID, Year, Month, Day, Time, Time_Zone,
         npoc_mgL, npoc_uM, npoc_flag, tdn_mgL, tdn_uM, tdn_flag,
         Analysis_rundate,  Run_notes, Field_notes
        # list columns in the order you want them
  )


```



## Visualize Data
```{#r Visualize Data, echo=FALSE, warning=FALSE, fig.width=16, fig.height=10}

data_plotting <- rbind(all_data)

#Order by Zone from Upland to Surface Water
data_plotting$Zone = factor(data_plotting$Zone, levels = c("UP", "SWAMP", "TR", "WC", "SW"))
data_plotting <- data_plotting[order(data_plotting$Zone), ]

#Order by Site from SWH, GCW, MSM, GWI order, which is oligohaline to polyhaline
data_plotting$Site = factor(data_plotting$Site, levels = c("SWH", "GCW", "MSM", "GWI"))
data_plotting <- data_plotting[order(data_plotting$Site), ]


data_plotting$Month_name <- month.name[data_plotting$Month]
data_plotting$months_factor <- factor(data_plotting$Month_name, levels = month.name)

#Plot samples to get a first look at concentrations (sanity check)
#group the data for plotting
data_plotting_all <- data_plotting %>%
  group_by(Site, Zone, months_factor) %>%
  mutate(row_num = factor(row_number())) %>%  # create row_num as factor per group
  ungroup()


data_plotting_all$Date <- as.Date(paste(data_plotting_all$Year, data_plotting_all$Month, data_plotting_all$Day, sep = "-"))


#Plot data and change colors based on Zone:
viz_NPOC_plot <- ggplot(data_plotting_all, aes(x = months_factor, y = npoc_mgL, fill = Zone)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "total")) +
  facet_grid( ~ Site, scales="free") +
  scale_fill_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = "NPOC (mg/L)", title = "Synoptic CB Porewater: NPOC 2025") +
  theme(
    panel.spacing = unit(.05, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) + 
  theme(text = element_text(size = 20))

print(viz_NPOC_plot)

viz_TDN_plot <- ggplot(data_plotting_all, aes(x = months_factor, y = tdn_mgL, fill = Zone)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "total")) +
  facet_grid( ~ Site, scales="free") +
  scale_fill_manual(values = c(
    "UP" = "#20063B",
    "TR" = "#FFBC42",
    "SWAMP" = "darkgrey",
    "WC" = "#419973",
    "SW" = "#25ABE6"
  )) +
  theme_classic() +
  labs(x = " ", y = "TDN (mg/L)", title = "Synoptic CB Porewater: TDN 2025") +
  theme(
    panel.spacing = unit(.05, "lines"), 
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) + 
  theme(text = element_text(size = 20))

print(viz_NPOC_plot)

```


## Write the 2023 file out to the folder 
```{r, echo=FALSE}

#write out all the lysimeter sample data 
write.csv(all_data, "FATE_DOC_DIC_TA.csv")

```

##END

