---
title: "Collate_FATE_Data"
author: "Zoe Read"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(lubridate)
```

#Read in and collate all the files in the DOC Processed Data folder 
```{r}

files <- list.files(path = "../../FATE Monitoring/DOC_data/Processed Data", pattern = "\\.csv$", full.names = TRUE)

data_list <- lapply(files, function(f) {
  df <- read.csv(f, stringsAsFactors = FALSE)  # avoids factors
  # df$Site <- as.character(df$Site)             # ensures character
  return(df)
})

# Combine all files
DOC_data <- bind_rows(data_list)

#remove the first unneeded column
DOC_data <- DOC_data[, -which(names(DOC_data) == "X")]
colnames(DOC_data)

DOC_data1 <- DOC_data %>% 
  mutate(Date = ymd(Date)) %>% 
  select(Project, Date, Time, Sample_Location, npoc_mgL, npoc_uM, npoc_flag, tdn_mgL, tdn_uM, tdn_flag)

```

#Read in and collate all the files in the DIC Processed Data folder - some data with no timestamps? 
```{r}

files <- list.files(path = "../../FATE Monitoring/DIC_data/Processed Data", pattern = "\\.csv$", full.names = TRUE)

data_list <- lapply(files, function(f) {
  df <- read.csv(f, stringsAsFactors = FALSE)  # avoids factors
  # df$Site <- as.character(df$Site)             # ensures character
  return(df)
})

# Combine all files
DIC_data <- bind_rows(data_list)

#remove the first unneeded column
DIC_data <- DIC_data[, -which(names(DIC_data) == "X")]

DIC_data1 <- DIC_data %>% 
  mutate(Date = ymd(Date)) %>% 
  group_by(Project, Date, Time, Sample_Location) %>% ##Average and sd across replicates
  summarise( 
    ic_mgL_sd = sd(ic_mgL, na.rm = TRUE),
    ic_uM_sd = sd(ic_uM, na.rm = TRUE),
    ic_mgL = mean(ic_mgL, na.rm = TRUE),
    ic_uM = mean(ic_uM, na.rm = TRUE),
    YSI_Temp_C = mean(YSI_Temp_C, na.rm = TRUE),
    YSI_Sal_ppt = mean(YSI_Sal_ppt, na.rm = TRUE),

    # Take the first value of all OTHER columns not mentioned above
    across(-c(ic_mgL, ic_mgL_sd, ic_uM, ic_uM_sd, YSI_Temp_C, YSI_Sal_ppt, Replicate), first),
    
    .groups = "drop"
  ) %>% 
  select(Project, Date, Time, Sample_Location, ic_mgL, ic_mgL_sd, ic_uM, ic_uM_sd, ic_flag) %>% 
  mutate(Date = if_else(Date == as.Date("2025-11-10"), as.Date("2025-10-11"), Date)) %>% ##Fix date entered incorrectly
  mutate(Time = if_else(Date == as.Date("2025-10-11") & Sample_Location == "Dock", "13:18", Time)) %>% ##Fix missing timestamps
  mutate(Time = if_else(Date == as.Date("2025-10-11") & Sample_Location == "Flume", "11:48", Time)) %>% ##Fix missing timestamps
  mutate(Time = if_else(Date == as.Date("2025-12-04") & Sample_Location == "Flume", "11:23", Time)) %>% ##Fix missing timestamps
  mutate(Time = if_else(Date == as.Date("2025-12-04") & Sample_Location == "Dock", "12:24", Time)) ##Fix missing timestamps

```

#Read in and collate all the files in the TA Processed Data folder 
```{r}

files <- list.files(path = "../../FATE Monitoring/TA_data", pattern = "processed.*\\.csv$", full.names = TRUE)

data_list <- lapply(files, function(f) {
  df <- read.csv(f, stringsAsFactors = FALSE)  # avoids factors
  # df$Site <- as.character(df$Site)             # ensures character
  return(df)
})

# Combine all files
TA_data <- bind_rows(data_list)

colnames(TA_data)

##Match DIC/DOC columns names
TA_data1 <- TA_data %>% 
  mutate(Project = "FATE", 
         Date = as.Date(sample_datetime), 
         Time = substr(sample_datetime, 12, 16), 
         location = gsub("serc_gcrew_flume", "Flume", location)) %>% 
  rename(Sample_Location = location) %>% 
  select(Project, Date, Time, Sample_Location, alk_umol_kgsw_avg, alk_umol_kgsw_sd, alk_mmol_l_avg, alk_mmol_l_sd, sal_ppt, h2o_temp_c, sample_datetime_utc)

```

##Combine dataframes
```{r combine bottle data}

DIC_DOC <- merge(DIC_data1, DOC_data1, by = c("Project", "Date", "Time", "Sample_Location"), all = TRUE)
DIC_DOC <- DIC_DOC %>% 
  filter(Sample_Location != "Dock")


DIC_DOC_TA <- merge(DIC_DOC, TA_data1, by = c("Project", "Date", "Time", "Sample_Location"), all = TRUE)
DIC_DOC_TA <- DIC_DOC_TA %>% 
  rename(Time_Local = Time)


##Mismatch between DIC/DOC and TA times on 2025-08-13


```

##Merge with metadata
```{r metadata}

meta_2025 <- read.csv("../../FATE Monitoring/Metadata/FATE_Monitoring_Metadata_2025.csv", colClasses = "character")
meta_2026 <- read.csv("../../FATE Monitoring/Metadata/FATE_Monitoring_Metadata_2026.csv", colClasses = "character")

meta <- bind_rows(meta_2025, meta_2026)

meta1 <- meta %>% 
  mutate(Date = mdy(Date)) %>% 
  select(-c(DIC_24ml, DIC_ex_1ml, SO4.H2S_5ml, Nutr_10ml, DOC_20ml, TA_250ml))

all_data <- DIC_DOC_TA %>% 
  left_join(meta1, by = c("Date", "Time_Local", "Sample_Location"))

final_data <- all_data %>% 
  select(Project, Date, Time_Local, Sample_Location, ic_mgL, ic_mgL_sd, ic_uM, ic_uM_sd, ic_flag, npoc_mgL, npoc_uM, npoc_flag, tdn_mgL, tdn_uM, tdn_flag, alk_umol_kgsw_avg, alk_umol_kgsw_sd, alk_mmol_l_avg, alk_mmol_l_sd, sal_ppt, h2o_temp_c, sample_datetime_utc)

```


## Subset data and write out collated files
```{r, echo=FALSE}

final_data_2023 <- subset(final_data, year(Date) == 2023)
final_data_2024 <- subset(final_data, year(Date) == 2024)
final_data_2025 <- subset(final_data, year(Date) == 2025)

##Write out annual data files
write.csv(final_data_2023, "FATE_Monitoring_DIC_DOC_2023.csv", row.names = FALSE)
write.csv(final_data_2024, "FATE_Monitoring_DIC_DOC_2024.csv", row.names = FALSE)
write.csv(final_data_2025, "FATE_Monitoring_DIC_DOC_2025.csv", row.names = FALSE)

```

## Create dd file
```{r make metadata, include = FALSE}

colnames(final_data)

#pull the column names from the all_dat1 dataframe and create a new dataframe with them
dd <- data.frame(Column_Names = c(colnames(final_data)))
dd

dd$Unit <- ""
dd$Definition <- ""
dd$Column_Long_Name <- dd$Column_Names
dd$data_type <- ""
dd$Instrument_ifapplicable <- ""
dd$Method_ifapplicable <- ""

#add information about each line:
dd$Definition <-       c("Project name", 
                         "Date sample was collected (YYYY-MM-DD)", 
                         "Local time when sample was collected (HH:MM)", 
                         "Sampling Location (Flume or Dock)", 
                         "Sample ID", 
                         "Inorganic Carbon concentration mean of replicates (mg/L)", 
                         "Inorganic Carbon concentration standard deviation of replicates (mg/L)", 
                         "Inorganic Carbon concentration mean of replicates (umol/L)", 
                         "Inorganic Carbon concentration standard deviation of replicates (umol/L)", 
                         "Inorganic Carbon concentration flag (adl = above detection limit, bdl = below detection limit)", 
                         "Non-Purgeable Organic Carbon concentration (mg/L)", 
                         "Non-Purgeable Organic Carbon concentration (umol/L)", 
                         "Non-Purgeable Organic Carbon flag (adl = above detection limit, bdl = below detection limit)", 
                         "Total Dissolved Nitrogen concentration (mg/L)", 
                         "Total Dissolved Nitrogen concentration (umol/L)", 
                         "Total Dissolved Nitrogen flag (adl = above detection limit, bdl = below detection limit)", 
                         "alk_umol_kgsw_avg", 
                         "alk_umol_kgsw_sd", 
                         "alk_mmol_l_avg", 
                         "alk_mmol_l_sd", 
                         "sal_ppt", 
                         "h2o_temp_c", 
                         "sample_datetime_utc")

dd$Unit <-             c("NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "mg/L", 
                         "mg/L", 
                         "umol/L", 
                         "umol/L", 
                         "NA", 
                         "mg/L", 
                         "umol/L", 
                         "NA", 
                         "mg/L", 
                         "umol/L", 
                         "NA", 
                         "alk_umol_kgsw_avg", 
                         "alk_umol_kgsw_sd", 
                         "alk_mmol_l_avg", 
                         "alk_mmol_l_sd", 
                         "sal_ppt", 
                         "h2o_temp_c", 
                         "sample_datetime_utc")

dd$data_type <-        c("text", 
                         "text", 
                         "text", 
                         "text", 
                         "text", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "text", 
                         "numeric", 
                         "numeric", 
                         "text", 
                         "numeric", 
                         "numeric", 
                         "text", 
                         "alk_umol_kgsw_avg", 
                         "alk_umol_kgsw_sd", 
                         "alk_mmol_l_avg", 
                         "alk_mmol_l_sd", 
                         "sal_ppt", 
                         "h2o_temp_c", 
                         "sample_datetime_utc")

dd$Instrument_ifapplicable <-   c("NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "alk_umol_kgsw_avg", 
                         "alk_umol_kgsw_sd", 
                         "alk_mmol_l_avg", 
                         "alk_mmol_l_sd", 
                         "sal_ppt", 
                         "h2o_temp_c", 
                         "NA")


dd$Method_ifapplicable <- c("NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "alk_umol_kgsw_avg", 
                         "alk_umol_kgsw_sd", 
                         "alk_mmol_l_avg", 
                         "alk_mmol_l_sd", 
                         "sal_ppt", 
                         "h2o_temp_c", 
                         "NA")


#write out the data dictionary associated with the data:
write.csv(dd, "dd.csv", row.names = FALSE,  fileEncoding = "UTF-8")

```
