---
title: "Clean Sontek Files"
author: "Zoe Read"
date: "10-08-2026"
output: html_document
---

#Set up
```{r setup, include=FALSE}

# Load necessary packages 
require(pacman)
p_load(tidyverse, lubridate,  janitor, parsedate,  data.table, readxl,
       cowplot,ggpubr, plotrix, here, dplyr, purrr)

## Set a common timezone, so even if your computer switches timezones, everything is static
common_tz = "Etc/GMT+5"

```

## Combine all raw sontek files from Dropbox
```{r}

##Dropbox shared url in case it is needed
# dropbox_url <- "https://www.dropbox.com/scl/fo/g6t7g8mcq64wtv9fwqxvd/AMqe_jDI5xyMf0T0tyEsbfE?rlkey=q6pcb76vybzko19uahrc5kgsy&st=jfy0ig2e&dl=0"

##Change path to your dropbox 
path <- "C:/Users/readz/Smithsonian Dropbox/Zoe Read/GCREW_LOGGERNET_DATA/archive_data"

##Create a list of all sontek files in the archive
sontek_files <- dir(pattern = "Sontek.*\\.dat$", path = path, full.names = TRUE, recursive = TRUE)

##Read in Sontek files
combined_data <- sontek_files %>%
  map(~ read.table(.x, header = TRUE, stringsAsFactors = FALSE, skip = 1, sep = ",") %>%
        rename_with(~ gsub("velocity_x_zx_l", "velocity_x_zxl", .x)) %>% 
        rename_with(~ gsub("velocity_x_zx_r", "velocity_x_zxr", .x))) %>% 
  bind_rows(.id = "file_id") # .id tracks which row came from which file index

##Process Sontek files to remove rows with units, clean up column names, and set column types
sontek <- combined_data %>% 
  dplyr::slice(3:dplyr::n()) %>%
  janitor::clean_names() %>% 
  dplyr::mutate(
      # Ensure consistent types for datetime columns
      yyyy       = as.character(yyyy),
      mm         = as.character(mm),
      dd         = as.character(dd),
      hh         = as.character(hh),
      minute     = as.character(minute),
      ss         = as.character(ss),
      
      # Also force sample_number and sontek_id to character
      sample_number = as.character(sample_number),
      sontek_id     = as.character(sontek_id),

      # Parse timestamp safely (adjust if needed)
      timestamp = parsedate::parse_date(timestamp),
      datetime_raw = lubridate::force_tz(timestamp, tzone = common_tz),

      # Convert some numeric columns explicitly
      flowrate       = as.numeric(flowrate),
      stage          = as.numeric(stage),
      mean_velocity  = as.numeric(mean_velocity),
      total_volume   = as.numeric(total_volume),
      water_depth    = as.numeric(water_depth),
      index_velocity = as.numeric(index_velocity),
      cross_area     = as.numeric(cross_area),
      water_temperature = as.numeric(water_temperature)
    )


```

##Check sontek data
```{r}

## Check plots
sontek_chkplot_all <- ggplot(sontek, aes(timestamp, as.numeric(water_depth))) + 
                      geom_point() + theme_classic() + labs(x="Time Stamp", y="Water Depth (m)")
sontek_chkplot_all

##Check data less than 5 meters
sontek_chkplot <- ggplot(sontek, aes(timestamp, as.numeric(water_depth))) + 
                      geom_point() + theme_classic() + labs(x="Time Stamp", y="Water Depth (m)") + ylim(-0.5,5)
sontek_chkplot

```



## Pull out columns that we need
```{r}

##Clean sontek data
now()
sontek_subset <- sontek %>% 
  ##2040 timestamps? - remove any timestamps before current time 
  filter(timestamp < now()) %>% 
  ##Select necessary columns
  select(c(timestamp, flowrate, stage, mean_velocity, total_volume, water_depth, index_velocity, cross_area, water_temperature, system_status, velocity_x_zxc, velocity_x_zzc, velocity_x_zxl, velocity_x_zxr, batt_vol_sontek, pitch_angle, roll_angle, perc_submergance, range_water_surface, adj_water_depth, tot_vo_lpos, tot_vo_lneg, ecell, snr1, snr2, snr3, snr4, ice_score))

```


## Flag data that is out of instrument range
```{r}
colnames(sontek_subset)

final_data <- sontek_subset %>%
  mutate(flag = case_when(
    water_depth > 5 | water_depth < 0.05 ~ "OOR", 
    index_velocity > 5 | index_velocity < -5 ~ "OOR", 
    TRUE ~ NA_character_
  ))

##How many are OOR?
##Don't use water temperature from here

```


## Subset data and write out collated files
```{r, echo=FALSE}

final_data_2023 <- subset(final_data, year(timestamp) == 2023)
final_data_2024 <- subset(final_data, year(timestamp) == 2024)
final_data_2025 <- subset(final_data, year(timestamp) == 2025)

##Write out annual data files
write.csv(final_data_2023, "Sontek_2023_L1.csv", row.names = FALSE)
write.csv(final_data_2024, "Sontek_2024_L1.csv", row.names = FALSE)
write.csv(final_data_2025, "Sontek_2025_L1.csv", row.names = FALSE)

```


## Create dd file
```{r make metadata, include = FALSE}

colnames(final_data)

#pull the column names from the all_dat1 dataframe and create a new dataframe with them
dd <- data.frame(Column_Names = c(colnames(final_data)))
dd

dd$Unit <- ""
dd$Definition <- ""
dd$Column_Long_Name <- dd$Column_Names
dd$data_type <- ""

#add information about each line:
dd$Definition <-       c("Date and time of measurement (Etc/GMT+5)", 
                         "Flow rate (using defined channel geometry)", 
                         "Stage (water depth of the user-defined channel)", 
                         "Mean velocity", 
                         "Total water volume (based on all measured flow)", 
                         "Depth (relative to the top of the instrument)", 
                         "Downstream velocity in center of channel", 
                         "Cross-sectional area of user-defined channel", 
                         "Water temperature", 
                         "System status", 
                         "Center X velocity (downstream velocity in center of channel)", 
                         "Center Z velocity (vertical velocity in center of channel)", 
                         "Left X velocity (downstream velocity along the left bank)", 
                         "Right X velocity (downstream velocity along the right bank)", 
                         "Battery voltage", 
                         "Pitch angle in degrees", 
                         "Roll angle in degrees", 
                         "Percentage of sample during which instrument was submerged (100% means it was submerged for entire sample)", 
                         "Acoustically measured distance to water surface", 
                         "Measurement with atmospheric pressure removed", 
                         "Total volume of water in the positive downstream direction", 
                         "Total volume of water in the negative upstream direction", 
                         "Distance to the farthest measurement cell", 
                         "SNR for beam 1 (acoustic signal strength in dB)", 
                         "SNR for beam 2 (acoustic signal strength in dB)", 
                         "SNR for beam 3 (acoustic signal strength in dB)", 
                         "SNR for beam 4 (acoustic signal strength in dB)", 
                         "Values greater than 100 indicate possible surface ice", 
                         "QAQC Flag (OOR = Out of instrument range)")

dd$Unit <-             c("NA", 
                         "m^3/s", 
                         "m", 
                         "m/s", 
                         "m^3", 
                         "m", 
                         "m/s", 
                         "m^2", 
                         "degrees Celsius", 
                         "NA", 
                         "m/s", 
                         "m/s", 
                         "m/s", 
                         "m/s", 
                         "V", 
                         "angle in degrees", 
                         "angle in degrees", 
                         "Percentage", 
                         "m", 
                         "m H2O", 
                         "m^3", 
                         "m^3", 
                         "m", 
                         "dB", 
                         "dB", 
                         "dB", 
                         "dB", 
                         "NA", 
                         "NA")

dd$data_type <-        c("text", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "text", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "text")


#write out the data dictionary associated with the data:
write.csv(dd, "dd.csv", row.names = FALSE,  fileEncoding = "UTF-8")

```

##END