---
title: "02_conc_eqn_ML"
author: "Stephanie J. Wilson"
date: "2025-09-04"
output: pdf_document
---
```{r setup}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.duplicate.label = "allow")
```

```{r packages, warning=FALSE,include=FALSE}
library(tidyverse)
library(lubridate)
library(ModelMetrics)
library(rmarkdown)
library(caret)
library(randomForest)
library(ggpmisc)
library(RColorBrewer)
library(seacarb)
library(viridis)
library(patchwork)

```

```{r read data,include=FALSE}
rm(list=ls())
DIC_bottle_data <- read.csv("derived-data/DIC_bottle_data.csv")
DOC_bottle_data <- read.csv("derived-data/DOC_bottle_data.csv")
sensor_data <- read.csv("derived-data/sensor_data.csv")
if("DIC" %in% colnames(sensor_data))
{sensor_data=select(sensor_data, -DIC, -DOC)}
```

## DIC model - Machine Learning
```{r fit DIC model}

clean_dic_data <- DIC_bottle_data %>% 
  rename(temp = 'T') %>%
  filter(!is.na(DIC) & !is.na(pH) & !is.na(temp) & !is.na(S) & !is.na(DO))

clean_dic_data$datetime <- as.POSIXct(clean_dic_data$datetime, format = "%Y-%m-%d %H:%M:%S")
clean_dic_data$day_of_year <- as.numeric(format(clean_dic_data$datetime, "%j"))


#notes from convo with Qipei 
  #pay attention to if you data coverage and what is missing, but be cautious
  #if critical data is missing then you might want to not allow it to predict 
  #determine which parameter is more important if it is NA then remove the prediction
  #na.action is related to this

  #cross validation is the 5 in the 

  #after you have the time series and look at the range and see what 


#model equations
control <- trainControl(method="repeatedcv",number=5,repeats=3,search="random")
DIC_RF_model <- train(DIC~DO+fDOM+S+pH+temp+H+day_of_year,
                      data=clean_dic_data,method="rf",na.action = na.roughfix,
                      metric="RMSE",tuneLength=15, trControl=control)
TA_RF_model <- train(TA~DO+fDOM+S+pH+temp+H+day_of_year,
                      data=clean_dic_data,method="rf",na.action = na.roughfix,
                      metric="RMSE",tuneLength=15, trControl=control)

#model performance
DIC_predicted <- predict(DIC_RF_model,clean_dic_data,na.action = na.roughfix)
a <- rmse(DIC_predicted,clean_dic_data$DIC)
b <- R2(DIC_predicted,clean_dic_data$DIC)
paste("DIC model statistics"," R2","=",round(b,digit=2), "RMSE","=",round(a,digit=0))

TA_predicted <- predict(TA_RF_model,clean_dic_data,na.action = na.roughfix)
c <- rmse(TA_predicted,clean_dic_data$TA)
d <- R2(TA_predicted,clean_dic_data$TA)
paste("TA model statistics"," R2","=",round(d,digit=2), "RMSE","=",round(c,digit=0))
rm(a, b, c, d)



#plot the model predicted vs. measured 
plot_DIC <- as.data.frame(DIC_predicted)
plot_DIC$DIC_meas <- clean_dic_data$DIC

p_model_DIC<-ggplot(plot_DIC,aes(x=DIC_predicted,y=DIC_meas))+
  geom_point(size=3) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black", size = 1)+
  labs(x = expression(paste("Measured DIC"," (",mu,"mol"," L"^-1,")")),
       y = expression(paste("Predicted DIC"," (",mu,"mol"," L"^-1,")")),
       color="",
       tag = "")+
  stat_smooth(method = "lm",se = FALSE)+
  theme_bw()+
  theme(aspect.ratio = 1,
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        plot.title = element_text(hjust = 0.5), 
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 12),
        axis.title =  element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.text.x = element_text(size = 12))
p_model_DIC




plot_TA <- as.data.frame(TA_predicted)
plot_TA$TA_meas <- clean_dic_data$TA

p_model_TA<-ggplot(plot_TA,aes(x=TA_predicted ,y=TA_meas))+
  geom_point(size=3) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black", size = 1)+
  labs(x = expression(paste("Measured TA"," (",mu,"mol"," L"^-1,")")),
       y = expression(paste("Predicted TA"," (",mu,"mol"," L"^-1,")")),
       color="",
       tag = "")+
  stat_smooth(method = "lm",se = FALSE)+
  theme_bw()+
  theme(aspect.ratio = 1,
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        plot.title = element_text(hjust = 0.5), 
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 12),
        axis.title =  element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.text.x = element_text(size = 12))
p_model_TA

```


## DOC model - Machine Learning
```{r fit DOC model}

clean_doc_data <- DOC_bottle_data %>% 
  rename(temp = 'T') %>%
  filter(!is.na(DIC) & !is.na(pH) & !is.na(temp) & !is.na(S) & !is.na(DO))

clean_doc_data$datetime <- as.POSIXct(clean_doc_data$datetime, format = "%Y-%m-%d %H:%M:%S")
clean_doc_data$day_of_year <- as.numeric(format(clean_doc_data$datetime, "%j"))


#notes from convo with Qipei 
  #pay attention to if you data coverage and what is missing, but be cautious
  #if critical data is missing then you might want to not allow it to predict 
  #determine which parameter is more important if it is NA then remove the prediction
  #na.action is related to this

  #cross validation is the 5 in the 

  #after you have the time series and look at the range and see what 


#model equations
control <- trainControl(method="repeatedcv",number=5,repeats=3,search="random")
DOC_RF_model <- train(DIC~DO+fDOM+S+pH+temp+H+day_of_year,
                      data=clean_doc_data,method="rf",na.action = na.roughfix,
                      metric="RMSE",tuneLength=15, trControl=control)

#model performance
DOC_predicted <- predict(DOC_RF_model,clean_doc_data,na.action = na.roughfix)
a <- rmse(DOC_predicted, clean_doc_data$DOC)
b <- R2(DOC_predicted, clean_doc_data$DOC)
paste("DOC model statistics"," R2","=",round(b,digit=2), "RMSE","=",round(a,digit=0))


#plot the model predicted vs. measured 
plot_DOC <- as.data.frame(DOC_predicted)
plot_DOC$DOC_meas <- clean_doc_data$DOC

p_model_DIC<-ggplot(plot_DOC,aes(x=DIC_predicted,y=DIC_meas))+
  geom_point(size=3) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black", size = 1)+
  labs(x = expression(paste("Measured DIC"," (",mu,"mol"," L"^-1,")")),
       y = expression(paste("Predicted DIC"," (",mu,"mol"," L"^-1,")")),
       color="",
       tag = "")+
  stat_smooth(method = "lm",se = FALSE)+
  theme_bw()+
  theme(aspect.ratio = 1,
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        plot.title = element_text(hjust = 0.5), 
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 12),
        axis.title =  element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.text.x = element_text(size = 12))
p_model_DIC


```


# predict vars over the whole sensor dataset 
```{r add concentration to sensor data, warning=FALSE}
DIC_ts <- 10^predict(DIC_model, sensor_data, na.action = na.roughfix)
DOC_ts <- 10^predict(DOC_model, sensor_data, na.action = na.roughfix) #with fDOM
TA_ts  <- 10^predict(TA_model, sensor_data, na.action = na.roughfix)

#fDOM should be within 0.9 to 80 QSU
#DOC_ts <- ifelse(is.na(DOC_ts_a), DOC_ts_b, DOC_ts_a)

sensor_data_withpreds <- tibble(sensor_data, DIC_ts, DOC_ts, TA_ts)
```


#Remove predicted values when critical predictors are not there or out of bounds
```{r clean sensor data}

#remove data when critical predictors are missing
  #DIC
DIC_ts[which((is.na(sensor_data$fDOM)==TRUE)&(is.na(sensor_data$DO)==TRUE))]<-NA
DIC_ts[which(is.na(sensor_data$S)==TRUE)]<-NA
  #DOC
DOC_ts[which((is.na(sensor_data$fDOM)==TRUE)&(is.na(sensor_data$pH)==TRUE))]<-NA
#DOC_ts[which(is.na(sensor_data$fDOM)==TRUE)]<-NA
  #TA
TA_ts[which((is.na(sensor_data$pH)==TRUE)&(is.na(sensor_data$S)==TRUE))]<-NA
TA_ts[which(is.na(sensor_data$S)==TRUE)]<-NA


# removing modeled concentrations where predictors are out of bounds
a <- which(sensor_data$pH<5 | sensor_data$pH>9)
b <- which(sensor_data$S<2 | sensor_data$S>20)
c <- which(sensor_data$T<2.5 | sensor_data$T>30)
d <- which(sensor_data$DO<0.2 | sensor_data$DO>11)
e <- which(sensor_data$fDOM<2 | sensor_data$fDOM>80)
filter <- unique(c(a, b, c, d, e))
DIC_ts[filter] <- NA
DOC_ts[filter] <- NA
TA_ts[filter] <- NA
rm(a, b)

all_data <- tibble(sensor_data_withpreds, DIC = DIC_ts, TA = TA_ts, DOC = DOC_ts)
```


```{r save sensor data}
all_data <- all_data %>% mutate_all(~ifelse(is.nan(.), NA, .))
all_data <- all_data %>% mutate_all(~ifelse(is.infinite(.), NA, .))
write.csv(all_data, "derived-data/all_data.csv", 
          row.names = FALSE)
```


```{r plot all data, echo=FALSE, warning=FALSE}
all_data <- mutate(all_data, year=year(datetime))
all_data$year <- as.factor(all_data$year)
all_data$datetime<-as.POSIXct(all_data$datetime)


xbreak<-seq(as.POSIXct("2000-01-01"), as.POSIXct("2000-12-31"),"1 month")
labels<-month(xbreak,label=TRUE)
lims<-c(as.POSIXct('2000-01-01'), as.POSIXct('2000-12-31'))
labels<-month(xbreak,label=TRUE)

p1<- ggplot(data=all_data)+
  geom_line(aes(x=datetime,y=DIC,group=year,color = year),size=0.5)+
  scale_colour_manual(values=c("darkblue", "deeppink4"))+ 
  labs(x = "Month",
       y = expression(atop("DIC",paste("(",mu,"mol ","L"^-1,")"))),
       color = "year",
       group = "year")+
  #guides(color = guide_legend(title="year"))+
  theme_bw()+
  #scale_y_continuous(breaks = seq(1600,2600,200),limits=c(1600,2600))+
  #scale_x_datetime(breaks = xbreak,limits = lims,date_labels = "%b")+
  theme(legend.position = "right",
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        panel.border = element_rect(colour = "black", fill=NA, size=1),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

p2<- ggplot(data=all_data)+
  geom_line(aes(x=datetime,y=TA,group=year,color = year),size=0.5)+
  scale_colour_manual(values=c("darkblue", "deeppink4"))+ 
  labs(x = "Month",
       y = expression(atop("TA",paste("(",mu,"mol ","L"^-1,")"))),
       color = "year",
       group = "year")+
  #guides(color = guide_legend(title="year"))+
  theme_bw()+
  #scale_y_continuous(breaks = seq(1600,2600,200),limits=c(1600,2600))+
  #scale_x_datetime(breaks = xbreak,limits = lims,date_labels = "%b")+
  theme(legend.position = "right",
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        panel.border = element_rect(colour = "black", fill=NA, size=1),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

p3<- ggplot(data=all_data)+
  geom_line(aes(x=datetime,y=DOC,group=year,color = year),size=0.5)+
  scale_colour_manual(values=c("darkblue", "deeppink4"))+ 
  labs(x = "Month",
       y = expression(atop("DOC",paste("(",mu,"mol ","L"^-1,")"))),
       color = "year",
       group = "year")+
  #guides(color = guide_legend(title="year"))+
  theme_bw()+
  scale_y_continuous(limits=c(0,4000))+
  #scale_x_datetime(breaks = xbreak,limits = lims,date_labels = "%b")+
  theme(legend.position = "right",
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        panel.border = element_rect(colour = "black", fill=NA, size=1),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.text.x = element_text(size = 12))

p.ts <- (p1/p2/p3) + plot_layout(guides = "collect")
p.ts
```       

