---
title: "Collate_TidalSurvey_Data"
author: "Zoe Read"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(readxl)
library(tidyr)
library(tibble)
library(lubridate)
library(hms)
library(readr)
library(here)
```

#Read in and collate all the files in the DOC Processed Data folder 
```{r}

here()
##List all processed files and pull them in individually to format them
files <- list.files(path = "../../Tidal_Surveys/Processed_Data", pattern = "DOC.*\\.csv$", full.names = TRUE, recursive = TRUE)

data1 <- read_csv(files[1], id = "filename", col_types = cols(.default = col_character()))
colnames(data1)
data1 <- data1 %>% 
  mutate(Date = mdy(Date))

data2 <- read_csv(files[2], id = "filename", col_types = cols(.default = col_character()))
colnames(data2)
data2 <- data2 %>% 
  mutate(Date = mdy(Date))

data3 <- read_csv(files[3], id = "filename", col_types = cols(.default = col_character()))
colnames(data3)
data3_formatted <- data3 %>% 
  mutate(Replicate = Sample_ID, 
         Sample_ID = sample_name, 
         Date = ymd(Sample_Date)) %>% 
  mutate(
  Time_Local = 
    ifelse(is.na(Time), NA,
    paste0(
      substr(sprintf("%04d", as.numeric(Time)), 1, 2),
      ":",
      substr(sprintf("%04d", as.numeric(Time)), 3, 4)))) %>% 
  select(-sample_name, -Time) 

# Combine all files
DOC_data <- bind_rows(data1, data2, data3_formatted)

##Clean data
DOC_data1 <- DOC_data %>% 
  ##Use non-isco samples if available but if not, use isco samples
  ##Make a column for "isco"
  ##If n > 1 then remove the isco sample 
  mutate(ISCO = ifelse(str_detect(Sample_ID, "isco"), "isco", NA)) %>% 
  mutate(Sample_ID = ifelse(str_detect(Sample_ID, "isco"), gsub("_isco", "", Sample_ID), Sample_ID)) %>% 
  group_by(Sample_ID) %>% 
  mutate(n = n()) %>% 
  filter(!(ISCO %in% "isco" & n == 2)) %>% 
  summarise( 
    npoc_mgL_sd = sd(as.numeric(npoc_mgL), na.rm = TRUE),
    npoc_uM_sd = sd(as.numeric(npoc_uM), na.rm = TRUE),
    npoc_mgL = mean(as.numeric(npoc_mgL), na.rm = TRUE),
    npoc_uM = mean(as.numeric(npoc_uM), na.rm = TRUE),
    tdn_mgL_sd = sd(as.numeric(tdn_mgL), na.rm = TRUE),
    tdn_uM_sd = sd(as.numeric(tdn_uM), na.rm = TRUE),
    tdn_mgL = mean(as.numeric(tdn_mgL), na.rm = TRUE),
    tdn_uM = mean(as.numeric(tdn_uM), na.rm = TRUE),
    
    # Take the first value of all OTHER columns not mentioned above
    across(-c(npoc_mgL, npoc_mgL_sd, npoc_uM, npoc_uM_sd, tdn_mgL, tdn_mgL_sd, tdn_uM, tdn_uM_sd), first),
    
    .groups = "drop"
  ) %>% 
  filter(!str_detect(Sample_ID, "Pair")) %>% ##Remove paired test samples
  filter(!str_detect(Sample_ID, "INCUB")) %>% ##Remove incubation samples
  mutate(Sample_ID = gsub("ESTUARY", "EST", Sample_ID)) %>% ##Standardize sample ids
  mutate(Sample_ID = gsub("LatT_GCW_WE1-GW2_20240715_1650", "LatT_GCW_WE1_20240715_1650", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("LatT_GCW_WE2-GW2_20240715_1730", "LatT_GCW_WE2_20240715_1730", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("LatT_GCW_WE3-GW3_20240718_0730", "LatT_GCW_WE3_20240718_0730", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("LatT_GCW_WE4-GW4_20240718_0745", "LatT_GCW_WE4_20240718_0745", Sample_ID)) %>% 
  select(Sample_ID, Sample_Type, Date, Time_Local, Time_EST, npoc_mgL, npoc_mgL_sd, npoc_uM, npoc_uM_sd, npoc_flag, tdn_mgL, tdn_mgL_sd, tdn_uM, tdn_uM_sd, tdn_flag) ##Select necessary columns

```

#Read in and collate all the files in the DIC Processed Data folder 
```{r}

##List all processed files and pull them in individually to format them
files <- list.files(path = "../../Tidal_Surveys/Processed_Data", pattern = "DIC.*\\.csv$", full.names = TRUE, recursive = TRUE)

data1 <- read_csv(files[1], id = "filename", col_types = cols(.default = col_character()))
colnames(data1)
data1 <- data1 %>% 
  mutate(Date = mdy(Date))

data2 <- read_csv(files[2], id = "filename", col_types = cols(.default = col_character()))
colnames(data2)
data2 <- data2 %>% 
  mutate(Date = mdy(Date))

data3 <- read_csv(files[3], id = "filename", col_types = cols(.default = col_character()))
colnames(data3)
data3_formatted <- data3 %>% 
  mutate(Replicate = Sample_ID, 
         Sample_ID = sample_name, 
         Date = ymd(Sample_Date)) %>% 
  mutate(
  Time_Local = 
    ifelse(is.na(Time), NA,
    paste0(
      substr(sprintf("%04d", as.numeric(Time)), 1, 2),
      ":",
      substr(sprintf("%04d", as.numeric(Time)), 3, 4)))) %>% 
  select(-sample_name, -Time) 

# Combine all files
DIC_data <- bind_rows(data1, data2, data3_formatted)

##Clean data
DIC_data1 <- DIC_data %>% 
  ##Use non-isco samples if available but if not, use isco samples
  ##Make a column for "isco"
  ##If n > 1 then remove the isco sample 
  mutate(ISCO = ifelse(str_detect(Sample_ID, "isco"), "isco", NA)) %>% 
  mutate(Sample_ID = ifelse(str_detect(Sample_ID, "isco"), gsub("_isco", "", Sample_ID), Sample_ID)) %>% 
  group_by(Sample_ID) %>% 
  mutate(n = n()) %>% 
  filter(!(ISCO %in% "isco" & n == 2)) %>% 
  # summarise( 
  #   ic_mgL_sd = sd(as.numeric(ic_mgL), na.rm = TRUE),
  #   ic_uM_sd = sd(as.numeric(ic_uM), na.rm = TRUE),
  #   ic_mgL = mean(as.numeric(ic_mgL), na.rm = TRUE),
  #   ic_uM = mean(as.numeric(ic_uM), na.rm = TRUE),
  #   
  #   # Take the first value of all OTHER columns not mentioned above
  #   across(-c(ic_mgL, ic_mgL_sd, ic_uM, ic_uM_sd), first),
  #   
  #   .groups = "drop"
  # ) %>% 
  filter(!str_detect(Sample_ID, "Pair")) %>% ##Remove paired test samples
  filter(!str_detect(Sample_ID, "INCUB")) %>% #Remove incubation samples
  mutate(Sample_ID = gsub("20232015", "20240215", Sample_ID)) %>% ##Fix incorrectly-entered dates
  mutate(Sample_ID = gsub("20230215", "20240215", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("20231215", "20240215", Sample_ID)) %>% 
  select(Sample_ID, ic_mgL, ic_uM, ic_flag) ##Select necessary columns

```

##Combine dataframes
```{r combine bottle data}

#check to see if all samples are present in the metadata 
DIC_data1$Sample_ID <- toupper(DIC_data1$Sample_ID)
DOC_data1$Sample_ID <- toupper(DOC_data1$Sample_ID)

all_present <- all(DIC_data1$Sample_ID %in% DOC_data1$Sample_ID)

if (all_present) {
  message("***All sample IDs are present in DOC data***")
} else {
  message("***Some sample IDs are missing from DOC data***")
  
  # Optional: Which ones are missing?
  missing_ids <- setdiff(DIC_data1$Sample_ID, DOC_data1$Sample_ID)
  print(missing_ids)
}

all_present <- all(DOC_data1$Sample_ID %in% DIC_data1$Sample_ID)

if (all_present) {
  message("***All sample IDs are present in DIC data***")
} else {
  message("***Some sample IDs are missing from DIC data***")
  
  # Optional: Which ones are missing?
  missing_ids <- setdiff(DOC_data1$Sample_ID, DIC_data1$Sample_ID)
  print(missing_ids)
}

##Merge DIC and DOC data
DIC_DOC <- merge(DOC_data1, DIC_data1, by = "Sample_ID", all = TRUE)

##Add missing metadata
DIC_DOC <- DIC_DOC %>% 
  mutate(Date = case_when(
    str_detect(Sample_ID, "20240209") ~ as.Date("2024-02-09"), 
    str_detect(Sample_ID, "20240215") ~ as.Date("2024-02-15"), 
    TRUE ~ Date)) %>% 
  mutate(Sample_Type = case_when(
    str_detect(Sample_ID, "FLUME_20240215_SW_1500") ~ "SW", 
    str_detect(Sample_ID, "FLUME_20240215_FW_1") ~ "FW", 
    TRUE ~ Sample_Type)) %>% 
  mutate(Sample_ID = gsub("LATT_GCW_T1_20240715_1100", "LATT_GCW_T1", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("LATT_GCW_T2_20240715_1200", "LATT_GCW_T2", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("EST1_20240715_1730", "EST1", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("EST2_20240715_1730", "EST2", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("EST3_20240715_1730", "EST3", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("EST_20240718_1046", "EST4", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("EST_20240718_1521", "EST5", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("TR1_20240715_1530", "TR1", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("TR2_20240717_1130", "TR2", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("UP1-FW1_20240715_1500", "UP1", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("UP2-FW1_20240715_1515", "UP2", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("WC1_20240715_1600", "WC1", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("WC2_20240715_1630", "WC2", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("WE1_20240715_1650", "WE1", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("WE2_20240715_1730", "WE2", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("WE3_20240718_0730", "WE3", Sample_ID)) %>% 
  mutate(Sample_ID = gsub("WE4_20240718_0745", "WE4", Sample_ID)) %>% 
  	
  mutate(Sample_ID = gsub("LATT_GCW_", "", Sample_ID))

```


#Read in and collate all the files in the TA Processed Data folder 
```{#r}

files <- list.files(path = "../../Tidal_Surveys/Processed_Data", pattern = "TA.*\\.csv$", full.names = TRUE, recursive = TRUE)
files

data1 <- read_csv(files[1], id = "filename", col_types = cols(.default = col_character()))
colnames(data1)

data_list <- lapply(files, function(f) {
  df <- read.csv(f, stringsAsFactors = FALSE)  # avoids factors
  # df$Site <- as.character(df$Site)             # ensures character
  return(df)
})

# Combine all files
TA_data <- bind_rows(data_list)

#remove the first unneeded column
TA_data <- TA_data[, -which(names(TA_data) == "X")]

##Match DIC/DOC columns names
TA_data1 <- TA_data %>% 
  mutate(Project = "FATE", 
         TA_mmolL = Alk_GP_avg/1000, 
         Date = mdy(date), 
         Time = substr(time, 1, 5), 
         location = gsub("Marsh_weir", "Flume", location)) %>% 
  rename(Sample_Location = location) %>% 
  select(Project, Date, Time, Sample_Location, sample_id, TA_mmolL)

```

##Combine dataframes
```{#r combine bottle data}

DIC_DOC_TA <- merge(DIC_DOC, TA_data1, by = c("Project", "Date", "Time", "Sample_Location"), all = TRUE)

DIC_DOC_TA <- DIC_DOC_TA %>% 
  rename(Time_Local = Time)

```

##Pull in metadata
```{r metadata}

files <- list.files(path = "../../Tidal_Surveys/Raw_Data", pattern = "Metadata.*\\.csv$", full.names = TRUE, recursive = TRUE)
files

data1 <- read_csv(files[1], col_types = cols(.default = col_character()))
colnames(data1)
data1_formatted <- data1 %>% 
  mutate(Date = mdy(Date), 
         Sample_Location = Site) %>% 
  select(Sample_Location, Date, Time_Local, Time_EST, Sample_Type, Sample_ID, Notes)

data2 <- read_csv(files[2], col_types = cols(.default = col_character()))
colnames(data2)
data2_formatted <- data2 %>% 
  mutate(Date = mdy(Date), 
         Sample_Location = Site) %>% 
  select(Sample_Location, Date, Time_Local, Time_EST, Sample_Type, Sample_ID, Notes)

data3 <- read_csv(files[3], col_types = cols(.default = col_character()))
colnames(data3)
data3_formatted <- data3 %>% 
  rename(Site = site, 
         Sample_Type = sample_type, 
         Sample_ID= sample_id, 
         Time_Local = time_sampled_edt, 
         Time_EST = time_sampled_est) %>% 
  mutate(Date = mdy(date), 
         Sample_Location = Site) %>% 
  select(Sample_Location, Date, Time_Local, Time_EST, Sample_Type, Sample_ID, Notes)

data4 <- read_csv(files[4], col_types = cols(.default = col_character()))
colnames(data4)
data4_formatted <- data4 %>% 
  rename(Time_Local = Time_collected_local, 
         Time_EST = Time_collected_EST) %>% 
  mutate(Date = mdy(Date_collected), 
         Sample_Location = Site) %>% 
  select(Sample_Location, Date, Time_Local, Time_EST, Sample_Type, Sample_ID, Notes)

meta <- bind_rows(data1_formatted, data2_formatted, data3_formatted, data4_formatted)

meta1 <- meta %>% 
  filter(!str_detect(Sample_ID, "PAIR")) %>% 
  filter(!str_detect(Sample_ID, "DOCK")) %>% 
  filter(!str_detect(Sample_ID, "Pair")) %>% 
  filter(!str_detect(Sample_ID, "Dock")) %>% 
  filter(year(Date) < 2026) %>% 
  mutate(Sample_ID = gsub("-", "", Sample_ID))

```

##Check if samples are in metadata
```{r}

DIC_DOC$Sample_ID <- toupper(DIC_DOC$Sample_ID)
meta1$Sample_ID <- toupper(meta1$Sample_ID)

all_present <- all(DIC_DOC$Sample_ID %in% meta1$Sample_ID)

if (all_present) {
  message("All sample IDs are present in metadata.")
} else {
  message("Some sample IDs are missing from metadata.")
  
  # Optional: Which ones are missing?
  missing_ids <- setdiff(DIC_DOC$Sample_ID, meta1$Sample_ID)
  print(missing_ids)
}

##Merge data
all_data <- DIC_DOC %>%
  left_join(meta1, by = c("Sample_ID", "Sample_Type", "Date", "Time_Local", "Time_EST"))

```


## Subset data and write out collated files
```{r, echo=FALSE}

final_data <- all_data %>% 
  separate(Sample_ID, into = c("Loc", "DateID", "Type", "Replicate"), sep = "_", extra = "merge") %>% 
  mutate(Replicate = ifelse(is.na(Replicate), Loc, Replicate)) %>% 
  mutate(Sample_Location = "Flume") %>% 
  select(Sample_Location, Sample_Type, Replicate, Date, Time_Local, Time_EST, ic_mgL, ic_uM, ic_flag, npoc_mgL, npoc_mgL_sd, npoc_uM, npoc_uM_sd, npoc_flag, tdn_mgL, tdn_mgL_sd, tdn_uM, tdn_uM_sd, tdn_flag, Notes)


final_data_2023 <- subset(final_data, year(Date) == 2023)
final_data_2024 <- subset(final_data, year(Date) == 2024)

##Write out annual data files
write.csv(final_data_2023, "Tidal_Survey_DIC_DOC_2023.csv", row.names = FALSE)
write.csv(final_data_2024, "Tidal_Survey_DIC_DOC_2024.csv", row.names = FALSE)

```

## Create dd file
```{r make metadata, include = FALSE}

colnames(final_data)

#pull the column names from the all_dat1 dataframe and create a new dataframe with them
dd <- data.frame(Column_Names = c(colnames(final_data)))
dd

dd$Unit <- ""
dd$Definition <- ""
dd$Column_Long_Name <- dd$Column_Names
dd$data_type <- ""
dd$Instrument_ifapplicable <- ""
dd$Method_ifapplicable <- ""

#add information about each line:
dd$Definition <-       c("Project name", 
                         "Date sample was collected (YYYY-MM-DD)", 
                         "Local time when sample was collected (HH:MM)", 
                         "Sampling Location (Flume or Dock)", 
                         "Sample ID", 
                         "Inorganic Carbon concentration mean of replicates (mg/L)", 
                         "Inorganic Carbon concentration standard deviation of replicates (mg/L)", 
                         "Inorganic Carbon concentration mean of replicates (umol/L)", 
                         "Inorganic Carbon concentration standard deviation of replicates (umol/L)", 
                         "Inorganic Carbon concentration flag (adl = above detection limit, bdl = below detection limit)", 
                         "Non-Purgeable Organic Carbon concentration (mg/L)", 
                         "Non-Purgeable Organic Carbon concentration (umol/L)", 
                         "Non-Purgeable Organic Carbon flag (adl = above detection limit, bdl = below detection limit)", 
                         "Total Dissolved Nitrogen concentration (mg/L)", 
                         "Total Dissolved Nitrogen concentration (umol/L)", 
                         "Total Dissolved Nitrogen flag (adl = above detection limit, bdl = below detection limit)", 
                         "Total Alkalinity (mmol/L)")

dd$Unit <-             c("NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "mg/L", 
                         "mg/L", 
                         "umol/L", 
                         "umol/L", 
                         "NA", 
                         "mg/L", 
                         "umol/L", 
                         "NA", 
                         "mg/L", 
                         "umol/L", 
                         "NA", 
                         "mmol/L")

dd$data_type <-        c("text", 
                         "text", 
                         "text", 
                         "text", 
                         "text", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "numeric", 
                         "text", 
                         "numeric", 
                         "numeric", 
                         "text", 
                         "numeric", 
                         "numeric", 
                         "text", 
                         "numeric")

dd$Instrument_ifapplicable <-   c("NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Shimadzu TOC", 
                         "Titrator?")


dd$Method_ifapplicable <- c("NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "NA", 
                         "Titrator?")


#write out the data dictionary associated with the data:
write.csv(dd, "dd.csv", row.names = FALSE,  fileEncoding = "UTF-8")

```

##END
